kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc 
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: jenkins
